# Generated by Django 2.1.4 on 2019-01-15 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=140)),
                ('comment_type', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('p_comment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='mysite.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_type', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('flag', models.IntegerField(default=0)),
                ('comment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mysite.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('concernnum', models.IntegerField(default=0)),
                ('fannum', models.IntegerField(default=0)),
                ('weibonum', models.IntegerField(default=0)),
                ('messagenum', models.IntegerField(default=0)),
                ('touxiangimg', models.ImageField(default='', upload_to='img')),
                ('follow_list', models.ManyToManyField(blank=True, related_name='my_followers', to='mysite.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('weiboimg', models.ImageField(default='', upload_to='img')),
                ('videolink', models.CharField(default='', max_length=140)),
                ('Comment_count', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_list',
            field=models.ManyToManyField(blank=True, related_name='topic_Weibo', to='mysite.Weibo'),
        ),
        migrations.AddField(
            model_name='mention',
            name='to_weibo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mysite.Weibo'),
        ),
        migrations.AddField(
            model_name='mention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.UserProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_weibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Weibo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.UserProfile'),
        ),
    ]
