NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.PrivateOrgThree.evoting.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.PrivateOrgThree.evoting.com-cert.pem
    OrganizationalUnitIdentifier: peer
