package app.mapper;

import app.entity.RD;
import app.entity.RDExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RDRMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sat May 25 09:30:40 CST 2019
     */
    int countByExample(RDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sat May 25 09:30:40 CST 2019
     */
    int deleteByExample(RDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sat May 25 09:30:40 CST 2019
     */
    int deleteByPrimaryKey(Integer servicedetailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sat May 25 09:30:40 CST 2019
     */
    int insert(RD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sat May 25 09:30:40 CST 2019
     */
    int insertSelective(RD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sat May 25 09:30:40 CST 2019
     */
    List<RD> selectByExample(RDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sat May 25 09:30:40 CST 2019
     */
    RD selectByPrimaryKey(Integer servicedetailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sat May 25 09:30:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") RD record, @Param("example") RDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sat May 25 09:30:40 CST 2019
     */
    int updateByExample(@Param("record") RD record, @Param("example") RDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sat May 25 09:30:40 CST 2019
     */
    int updateByPrimaryKeySelective(RD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sat May 25 09:30:40 CST 2019
     */
    int updateByPrimaryKey(RD record);
}